expert_menu:
  - id : "main_page"
    text : "메인페이지"
    sub_menues : null
  - id : "progress"
    text : "진행관리"
    sub_menues :
      - id : "new"
        text : "신규신청내역"
        sub_menues : null
      - id : "ing"
        text : "진행내역"
        sub_menues : null
      - id : "end"
        text : "중단/종료내역"
        sub_menues : null
  - id : "customer"
    text : "고객관리"
    sub_menues :
      - id : "adm"
        text : "고객조회/관리"
        sub_menues : null
      - id : "msg"
        text : "메일/메시지발송"
        sub_menues : null
      - id : "review"
        text : "리뷰관리"
        sub_menues : null
      - id : "schedule"
        text : "스케쥴관리"
        sub_menues : null
  - id : "calculate"
    text : "정산관리"
    sub_menues :
      - id : "account_adm"
        text : "내계좌조회"
        sub_menues : null
      - id : "taxbreakdown"
        text : "원천징수내역조회"
        sub_menues : null
      - id : "taxreceipt"
        text : "세금계산서내역조회"
        sub_menues : null
      - id : "devider"
        text : ""
        sub_menues : null
      - id : "request_withdraw"
        text : "출금신청"
        sub_menues : null
      - id : "check_withdraw"
        text : "출금진행조회"
        sub_menues : null
  - id : "my_info"
    text : "내정보관리"
    sub_menues :
      - id : "user_info_modify"
        text : "회원정보수정"
        sub_menues : null
      - id : "user_veri_modify"
        text : "검증항목수정신청/조회"
        sub_menues : null
      - id : "devider"
        text : ""
        sub_menues : null
      - id : "disciplinary"
        text : "신고 및 징계내역조회"
        sub_menues : null
      - id : "1to1qna"
        text : "1:1문의"
        sub_menues : null
      - id : "devider"
        text : ""
        sub_menues : null
      - id : "stats"
        text : "통계조회"
        sub_menues : null
      - id : "devider"
        text : ""
        sub_menues : null
      - id : "logout"
        text : "로그아웃"
        sub_menues : null
