specialized :
  - name : "연애와 결혼"
    comment : "이성과의 교제."
  - name : "인간 관계"
    comment : "부부, 자녀, 친구와의 관계 회복"
  - name : "꿈과 진로"
    comment : "적성발견, 꿈찾기"
  - name : "힐링"
    comment : "새로운 도전과 발전"
  - name : "명상"
    comment : "컴플렉스, 트라우마 극복"
  - name : "치유"
    comment : "왕따, 고아 등 환경에 의한 상처 회복"
  - name : "마음"
    comment : "명상을 통한 영적 훈련"
target: ["유아, 아동","청소년","청년","직장인","부부","노인"]
location: ["전국","서울","경기도","인천/부천","대구","경상북도","경상남도","부산","대전","충청도","광주","전라도","강원도","제주도"]
